spring:
  jpa:
    show-sql: true

    logging:
      level:
        org.hibernate.SQL: DEBUG
        org.hibernate.type: TRACE
        org.hibernate.orm.jdbc.bind: TRACE
        ru.practicum.shareit: DEBUG
